### ISSUE TITLE
No module named `kwat.constant.data_directory`

### ISSUE THREAD

**Issue by alex-wenzel** [KwatME/gsea#23]
I would guess that this error has to do with something that was refactored in the `Kwat.py` package, but since it affects my ability to run this code specifically and may or may not require changes to this repo as well, I wanted to post it here. I generated this by running the installation instructions in the README, and I installed both these packages as they are this afternoon (9/12/2021). It could be because `data_directory` is now `DATA_DIRECTORY` as of [this most recent commit](https://github.com/KwatME/kwat.py/tree/d6e5cd7fa44bc12bdc65913a6dbf5866dac44676/kwat/constant), but multiple scripts in `Kwat.py` import `data_directory`, see [search results](https://github.com/KwatME/kwat.py/search?q=data_directory).

```
Traceback (most recent call last):
  File "/Users/alexwenzel/Google_Drive/research/mesirov/projects/gsea_general/2021-09_work/2021-09-12_julia-gsea-precomp_v0.1.0/2021-09-12_julia-gsea-precomp_precomp-true_v0.1.0.py", line 8, in <module>
    import gsea
  File "/usr/local/lib/python3.9/site-packages/gsea/__init__.py", line 11, in <module>
    from ._compare_with_target import _compare_with_target
  File "/usr/local/lib/python3.9/site-packages/gsea/_compare_with_target.py", line 1, in <module>
    from kwat.array_array import (
  File "/usr/local/lib/python3.9/site-packages/kwat/__init__.py", line 1, in <module>
    from . import (
  File "/usr/local/lib/python3.9/site-packages/kwat/cell_line/__init__.py", line 1, in <module>
    from .rename import rename
  File "/usr/local/lib/python3.9/site-packages/kwat/cell_line/rename.py", line 1, in <module>
    from ._map_broad import _map_broad
  File "/usr/local/lib/python3.9/site-packages/kwat/cell_line/_map_broad.py", line 3, in <module>
    from ..constant import data_directory
  File "/usr/local/lib/python3.9/site-packages/kwat/constant/__init__.py", line 1, in <module>
    from .data_directory import data_directory
ModuleNotFoundError: No module named 'kwat.constant.data_directory'
```

**Comment by KwatME** [comment]
https://github.com/KwatME/kwat.py/issues/66

**Comment by KwatME** [comment]
ETA few days.
