### ISSUE TITLE
"PyJulia does not support" Python interpreter statically linked to libpython

### ISSUE THREAD

**Issue by alex-wenzel** [KwatME/gsea#3]
I followed the installation instructions with a completely fresh conda environment. The code section "Julia core algorithm" under "Test" runs fine, but the "Python interface" code fails with the following traceback.

```bash
(kwat-test)alexwenzel@Mesirovs-MacBook-Pro:old/:~$ python -c '
> from pandas import Series
> 
> el_sc = Series([-1., 1.], index=["A", "B"])
> 
> el1_ = ["B"]
> 
> from gsea import score_1_1
> 
> print(score_1_1(el_sc, el1_, pl=False))
> 
> print("Great!")
> '
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/Users/alexwenzel/Google_Drive/pyenvs/kwat-test/lib/python3.7/site-packages/gsea/__init__.py", line 1, in <module>
    from julia import Main
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/alexwenzel/Google_Drive/pyenvs/kwat-test/lib/python3.7/site-packages/julia/core.py", line 247, in load_module
    JuliaMainModule(self, fullname))
  File "/Users/alexwenzel/Google_Drive/pyenvs/kwat-test/lib/python3.7/site-packages/julia/core.py", line 149, in __init__
    self._julia = loader.julia
  File "/Users/alexwenzel/Google_Drive/pyenvs/kwat-test/lib/python3.7/site-packages/julia/core.py", line 239, in julia
    self.__class__.julia = julia = Julia()
  File "/Users/alexwenzel/Google_Drive/pyenvs/kwat-test/lib/python3.7/site-packages/julia/core.py", line 483, in __init__
    raise UnsupportedPythonError(jlinfo)
julia.core.UnsupportedPythonError: It seems your Julia and PyJulia setup are not supported.

Julia executable:
    julia
Python interpreter and libpython used by PyCall.jl:
    /Users/alexwenzel/.julia/conda/3/bin/python
    /Users/alexwenzel/.julia/conda/3/lib/libpython3.7m.dylib
Python interpreter used to import PyJulia and its libpython.
    /Users/alexwenzel/Google_Drive/pyenvs/kwat-test/bin/python
    /Users/alexwenzel/Google_Drive/pyenvs/kwat-test/lib/libpython3.7m.dylib

Your Python interpreter "/Users/alexwenzel/Google_Drive/pyenvs/kwat-test/bin/python"
is statically linked to libpython.  Currently, PyJulia does not fully
support such Python interpreter.

The easiest workaround is to pass `compiled_modules=False` to `Julia`
constructor.  To do so, first *reboot* your Python REPL (if this happened
inside an interactive session) and then evaluate:

    >>> from julia.api import Julia
    >>> jl = Julia(compiled_modules=False)

Another workaround is to run your Python script with `python-jl`
command bundled in PyJulia.  You can simply do:

    $ python-jl PATH/TO/YOUR/SCRIPT.py

See `python-jl --help` for more information.

For more information, see:

    https://pyjulia.readthedocs.io/en/latest/troubleshooting.html
```

Python version in environment is 3.7.1.

**Comment by KwatME** [comment]
This is because PyCall does not like Conda. Can you try these solutions? https://discourse.julialang.org/t/pycall-issues-possible-to-choose-conda-environment-as-path/54481

**Comment by KwatME** [comment]
The error comes from mismatching python interpreter used by julia and python.

When you installed PyCall, python seen was the global one.
When you installed pyjulia, which happened within the test environment, python used was the one in the testing environment.

Could you try to match the python used by both?

<img width="563" alt="Screen Shot 2021-07-21 at 22 07 35" src="https://user-images.githubusercontent.com/7741548/126588938-0be46340-97ad-49f0-84a6-8ca73f627c95.png">

**Comment by alex-wenzel** [comment]
If I run the following code,

```python
from pandas import Series

from julia.api import Julia
jl = Julia(compiled_modules=False)

el_sc = Series([-1., 1.], index=["A", "B"])

el1_ = ["B"]

from gsea import score_1_1

print(score_1_1(el_sc, el1_, pl=False))

print("Great!")
```

everything works fine. I'm not familiar enough with Julia though to know if doing this negates any speed boosts we'd get from switching to Julia. Would it be an issue?

**Comment by KwatME** [comment]
I don't know. Let me look into it.

**Comment by KwatME** [comment]
It says here that the keyword argument is for "incrementa" precmopilation. I'm not sure if the initial compilation will still work. I guess that speed is still fast because of the initial combination. 

https://pyjulia.readthedocs.io/en/latest/api.html

**Comment by KwatME** [comment]
Could you time this Julia old algorithm vs what people are using in python (old algorithm)?
